name: Submit ML-Benchmark Prediction
description: Submit metadata and details for an ML-Benchmark prediction submission
title: "ML-Benchmark prediction submission: [Your Model Name]"
labels: ["submission"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for submitting to CORDEX ML-Benchmark! 
        Please carefully fill out each field below with details about your prediction submission.
        For more information, see the format_predictions.

  # General Information
  - type: markdown
    attributes:
      value: "## General Information"

  # Institution Information
  - type: markdown
    attributes:
      value: "## Institution Details"

  - type: input
    id: institution_id
    attributes:
      label: Institution ID
      description: >
        Short acronym that uniquely identifies your institution
      placeholder: "IFCA"
    validations:
      required: true

  - type: input
    id: institution
    attributes:
      label: Institution Name
      description: >
        Full name of the institution responsible for the predictions
      placeholder: "Instituto de Física de Cantabria (IFCA), CSIC-Universidad de Cantabria"
    validations:
      required: true

  # Emulator Information
  - type: markdown
    attributes:
      value: "## Emulation Method Details"

  - type: input
    id: emulator_id
    attributes:
      label: Emulator identifier (`emulator_id`)
      description: >
        Identifier of the emulator model including the emulator name (e.g., DeepESD, XGBoost, ...) and the particular version, using the format \{emulator name\}-\{version\}. Note that any change or different versions need to be registered separately with the corresponding metadata. Each emulator model (submission) corresponds either to a single multivariate model or to two separate univariate models that provide predictions for maximum temperature and precipitation. In the case of univariate emulators, the models for each variable may differ (e.g., in their loss functions), so please specify this clearly in this field. For versions of the model using orography as predictor, use the tag `-orog` at the end of the identifier (e.g. `DeepESD-asym1-orog`).
      placeholder: "DeepESD-asym1"
    validations:
      required: true

  - type: textarea
    id: emulator
    attributes:
      label: Emulator Description
      description: >
        Detailed description of the emulation method including architecture and key 
        features, such as loss function, optimizer and hyperparameters, predictors used and 
        standardization, etc. Enough detail to distinguish the emulator and version from 
        any other version should be provided.
      placeholder: "Deep convolutional neural network including 3 convolution and one dense layer, with ReLU activation functions. Standardized input data at gridbox level using mean/std of reanalysis in training period. No bias adjustment performed. Training on historical and future experiments. For maximum temperature the MSE has been used as loss function, for precipitation the ASYM."
    validations:
      required: true

  - type: textarea
    id: hardware_training_details
    attributes:
      label: Hardware and Training Details
      description: >
        Include information about the hardware used to train the model (e.g., one node with two A100 GPUs), 
        training time per epoch and total training time, and inference time per year of predictions.
      placeholder: "Hardware: One node with two NVIDIA A100 GPUs (40GB). Training time: ~15 minutes per epoch, ~5 hours total (20 epochs). Inference time: ~2 minutes per year of predictions."
    validations:
      required: true

  # Output Characteristics
  - type: markdown
    attributes:
      value: "## Output and Realization Information"

  - type: dropdown
    id: stochastic_output
    attributes:
      label: Stochastic/Probabilistic Output
      description: >
        Does your emulator generate stochastic realizations (e.g. for generative methods)? Note that for these methods 5 realizations must be provided.
      options:
        - "no"
        - "yes"
    validations:
      required: true

  # References and Reproducibility
  - type: markdown
    attributes:
      value: "## References and Reproducibility"

  - type: input
    id: reference_url
    attributes:
      label: Reference URL
      description: >
        Reference information about the model (e.g., DOI, publication URL, technical documentation)
      placeholder: "https://doi.org/10.5194/gmd-15-6747-2022"
    validations:
      required: true

  - type: input
    id: reproducibility_url
    attributes:
      label: Repository for Reproducibility
      description: >
        URL with reproducibility information about the model (e.g., GitHub repository, Zenodo record)
      placeholder: "https://zenodo.org/records/6828304"
    validations:
      required: true

  # Additional Information
  - type: markdown
    attributes:
      value: "## Additional Notes (Optional)"

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: >
        Any additional information or notes that might be relevant
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Next Steps:** 
        After submission, the maintainers will review the registration details and will reply to this issue with comments. When ready a link to a secure form will be provided with the details to upload your data to contribute to this benchmark.
